spring:
  application:
    name: demo-mybatis

  datasource:
    url: jdbc:h2:mem:demo_mybatis # jdbc:h2:file:/data/demo
    username: sa
    password: password

  h2:
    console:
      enabled: true # Visit at http://localhost:8080/h2-console
